Admin/DemoDB2/DemoDB2/Controllers/SLIDERController.cs
using DemoDB2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoDB2.Controllers
{
    public class SLIDERController : Controller
    {
        // GET: SLIDER
        DBGiaDungEntities db = new DBGiaDungEntities();
        // GET: DanhSachPRODUCT
        //public ActionResult Index()
        //{
        //    return View(db.PRODUCTs.ToList());
        //}
        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                SLIDE sp = new SLIDE();
                return View(sp);
            }
        }
        [HttpPost]
        public ActionResult Create(SLIDE sp)
        {
            {
                try
                {
                    if (sp.UploadImage != null)
                    {
                        string filename = Path.GetFileNameWithoutExtension(sp.UploadImage.FileName);
                        string extent = Path.GetExtension(sp.UploadImage.FileName);
                        filename = filename + extent;
                        sp.image = "~/Content/images/" + filename;
                        sp.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                    }
                    db.SLIDEs.Add(sp);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Product");
                }
                catch
                {
                    return View();
                }
            }
        }
        public ActionResult Details(int id)
        {
            return View(db.SLIDEs.Where(s => s.slide_id == id).FirstOrDefault());
        }

        public ActionResult Edit(int id)
        {
            return View(db.SLIDEs.Where(s => s.slide_id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id, SLIDE sp)
        {
            if (sp.UploadImage != null)
            {
                string filename = Path.GetFileNameWithoutExtension(sp.UploadImage.FileName);
                string extent = Path.GetExtension(sp.UploadImage.FileName);
                filename = filename + extent;
                sp.image = "~/Content/images/" + filename;
                sp.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                var t = db.SLIDEs.AsNoTracking().Where(x => x.slide_id == id).FirstOrDefault();
                sp.image = t.image;
                db.Entry(sp).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            return View(db.SLIDEs.Where(s => s.slide_id == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id, SLIDE sp)
        {
            try
            {
                sp = db.SLIDEs.Where(s => s.slide_id == id).FirstOrDefault();
                db.SLIDEs.Remove(sp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("This data is using in other table, Error Delete!");
            }
        }
        public ActionResult Index()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                return View(db.SLIDEs.ToList());
            }
        }
    }
}

Admin/DemoDB2/DemoDB2/Views/SLIDER/Create.cshtml
@model DemoDB2.Models.SLIDE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Thêm mới Slide</h6>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Create", "SLIDER", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thông tin Slide</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @*<div class="form-group">
                                @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <img src="@Url.Content(Model.image)" width="150" height="150" id="previewImg" />
                                <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.slide_order, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.slide_order, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.slide_order, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Tạo" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Về Danh sách", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/SLIDER/Delete.cshtml
@model DemoDB2.Models.SLIDE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Xóa Slide</h6>
            </div>
            <div class="card-body">

                <h3>Bạn có chắc chắn muốn xóa không?</h3>
                <div>
                    <h4>Thông tin Slide</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.image)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.image)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.slide_order)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.slide_order)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.link)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.link)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-primary" /> |
                            @Html.ActionLink("Về Danh sách", "Index")
                        </div>
                    }
                    @section Scripts {
                        <!-- Bootstrap core JavaScript-->
                        <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                        <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                        <!-- Core plugin JavaScript-->
                        <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                        <!-- Custom scripts for all pages-->
                        <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                        <!-- Page level plugins -->
                        <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                        <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                        <!-- Page level custom scripts -->
                        <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/SLIDER/Details.cshtml
@model DemoDB2.Models.SLIDE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Chi tiết Slide</h6>
            </div>
            <div class="card-body">
                <h4>Thông tin Slide</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.image)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.image)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.slide_order)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.slide_order)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.link)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.link)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                    </dd>
                    <p>
                        @Html.ActionLink("Sửa", "Edit", new { id = Model.slide_id }) |
                        @Html.ActionLink("Về Danh sách", "Index")
                    </p>
                </dl>

                @section Scripts {
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/SLIDER/Edit.cshtml
@model DemoDB2.Models.SLIDE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Sửa Slide</h6>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Edit", "SLIDER", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thông tin Slide</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.slide_id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <img src="@Url.Content(Model.image)" width="150" height="150" id="previewImg" />
                                <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.slide_order, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.slide_order, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.slide_order, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Về Danh sách", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/SLIDER/Index.cshtml
@model IEnumerable<DemoDB2.Models.SLIDE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Danh sách Slide</h1>
    <p class="mb-4">
        @Html.ActionLink("Tạo Slide mới", "Create")
    </p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Thông tin Slide</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Hình Ảnh</th>
                            <th>Thứ Tự Slide</th>
                            <th>Link</th>
                            <th>Mô Tả</th>
                            <th>Chức Năng</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Hình Ảnh</th>
                            <th>Thứ Tự Slide</th>
                            <th>Link</th>
                            <th>Mô Tả</th>
                            <th>Chức Năng</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.image)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.slide_order)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.link)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.slide_id }) |
                                @Html.ActionLink("Chi tiết", "Details", new { id = item.slide_id }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.slide_id })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
@section Scripts{
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
}