Admin/DemoDB2/DemoDB2/Models/NEW.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class NEW
    {
        public NEW()
        {
            new_image = "~/Content/images/upload-i.jpg";
        }
        public int new_id { get; set; }
        public int tag_id { get; set; }
        public int new_catalog_id { get; set; }
        public int new_created_by { get; set; }
        public string tittle { get; set; }
        public string description { get; set; }
        public string new_image { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> new_created { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual CATALOG CATALOG { get; set; }
        public virtual TAG TAG { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}

Admin/DemoDB2/DemoDB2/Controllers/NEWsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoDB2.Models;

namespace DemoDB2.Controllers
{
    public class NEWsController : Controller
    {
        private DBGiaDungEntities db = new DBGiaDungEntities();

        // GET: NEWs
        public ActionResult Index()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                var nEWs = db.NEWs.Include(n => n.ADMIN).Include(n => n.CATALOG).Include(n => n.TAG);
                return View(nEWs.ToList());
            }
        }

        // GET: NEWs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NEW nEW = db.NEWs.Find(id);
            if (nEW == null)
            {
                return HttpNotFound();
            }
            return View(nEW);
        }

        // GET: NEWs/Create
        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                ViewBag.new_created_by = new SelectList(db.ADMINs, "admin_id", "username");
                ViewBag.new_catalog_id = new SelectList(db.CATALOGs, "catalog_id", "catalog_name");
                ViewBag.tag_id = new SelectList(db.TAGs, "tag_id", "tag_name");
                NEW nEW = new NEW();
                return View(nEW);
            }
        }

        // POST: NEWs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "new_id,tag_id,new_catalog_id,new_created_by,tittle,description,new_image,detail,new_created")] NEW nEW, HttpPostedFileBase UploadImage)
        {
            if (ModelState.IsValid)
            {
                var useradmin = Session["username"];
                var userCurrent = db.ADMINs.Where(x => x.username == useradmin.ToString()).FirstOrDefault();
                if (UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(UploadImage.FileName);
                    string extent = Path.GetExtension(UploadImage.FileName);
                    filename = filename + extent;
                    nEW.new_image = "~/Content/img/" + filename;
                    UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/img/"), filename));
                }
                nEW.new_created_by = Convert.ToInt32(userCurrent.admin_id);
                nEW.new_created = DateTime.Now;
                db.NEWs.Add(nEW);
                db.SaveChanges();
                ModelState.Clear();
                return RedirectToAction("Index");
            }
            ViewBag.new_created_by = new SelectList(db.ADMINs, "admin_id", "username", nEW.new_created_by);
            ViewBag.new_catalog_id = new SelectList(db.CATALOGs, "catalog_id", "catalog_name", nEW.new_catalog_id);
            ViewBag.tag_id = new SelectList(db.TAGs, "tag_id", "tag_name", nEW.tag_id);
            return View(nEW);
        }

        // GET: NEWs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NEW nEW = db.NEWs.Find(id);
            if (nEW == null)
            {
                return HttpNotFound();
            }
            ViewBag.new_created_by = new SelectList(db.ADMINs, "admin_id", "username", nEW.new_created_by);
            ViewBag.new_catalog_id = new SelectList(db.CATALOGs, "catalog_id", "catalog_name", nEW.new_catalog_id);
            ViewBag.tag_id = new SelectList(db.TAGs, "tag_id", "tag_name", nEW.tag_id);
            return View(nEW);
        }

        // POST: NEWs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "new_id,tag_id,new_catalog_id,new_created_by,tittle,description,new_image,detail,new_created")] NEW nEW,int id, HttpPostedFileBase UploadImage)
        {
            if (ModelState.IsValid)
            {
                if (UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(UploadImage.FileName);
                    string extent = Path.GetExtension(UploadImage.FileName);
                    filename = filename + extent;
                    nEW.new_image = "~/Content/img/" + filename;
                    UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/img/"), filename));
                    nEW.new_created = DateTime.Now;
                    db.Entry(nEW).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    var t = db.NEWs.AsNoTracking().Where(x => x.new_id == id).FirstOrDefault();
                    nEW.new_image = t.new_image;
                    nEW.new_created = DateTime.Now;
                    db.Entry(nEW).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.new_created_by = new SelectList(db.ADMINs, "admin_id", "username", nEW.new_created_by);
            ViewBag.new_catalog_id = new SelectList(db.CATALOGs, "catalog_id", "catalog_name", nEW.new_catalog_id);
            ViewBag.tag_id = new SelectList(db.TAGs, "tag_id", "tag_name", nEW.tag_id);
            return View(nEW);
        }

        // GET: NEWs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NEW nEW = db.NEWs.Find(id);
            if (nEW == null)
            {
                return HttpNotFound();
            }
            return View(nEW);
        }

        // POST: NEWs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NEW nEW = db.NEWs.Find(id);
            db.NEWs.Remove(nEW);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/DemoDB2/DemoDB2/Views/NEWs/Create.cshtml
@model DemoDB2.Models.NEW

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Thêm mới tin tức</h6>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Create", "NEWs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thông tin tin tức</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.tag_id, "tag_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("tag_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.tag_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.new_catalog_id, "new_catalog_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("new_catalog_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.new_catalog_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.new_created_by, "new_created_by", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("new_created_by", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.new_created_by, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.tittle, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tittle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tittle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.new_image, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <img src="@Url.Content(Model.new_image)" width="150" height="150" id="previewImg" />
                                <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.new_created, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.new_created, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.new_created, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Tạo" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Về Danh sách", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/NEWs/Delete.cshtml
@model DemoDB2.Models.NEW

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Xóa tin tức</h6>
            </div>
            <div class="card-body">

                <h3>Bạn có chắc chắn muốn xóa không?</h3>
                <div>
                    <h4>Thông tin tin tức</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.tittle)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.tittle)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.new_image)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.new_image)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.detail)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.detail)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.new_created)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.new_created)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.ADMIN.username)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ADMIN.username)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CATALOG.catalog_name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CATALOG.catalog_name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TAG.tag_name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TAG.tag_name)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-primary" /> |
                            @Html.ActionLink("Về Danh sách", "Index")
                        </div>
                    }
                    @section Scripts {
                        <!-- Bootstrap core JavaScript-->
                        <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                        <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                        <!-- Core plugin JavaScript-->
                        <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                        <!-- Custom scripts for all pages-->
                        <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                        <!-- Page level plugins -->
                        <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                        <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                        <!-- Page level custom scripts -->
                        <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/NEWs/Details.cshtml
@model DemoDB2.Models.NEW

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Chi tiết tin tức</h6>
            </div>
            <div class="card-body">
                <h4>Thông tin tin tức</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.tittle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.tittle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.new_image)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.new_image)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.detail)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.detail)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.new_created)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.new_created)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ADMIN.username)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ADMIN.username)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CATALOG.catalog_name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CATALOG.catalog_name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TAG.tag_name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TAG.tag_name)
                    </dd>
                    <p>
                        @Html.ActionLink("Sửa", "Edit", new { id = Model.new_id }) |
                        @Html.ActionLink("Về Danh sách", "Index")
                    </p>
                </dl>

                @section Scripts {
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->

Admin/DemoDB2/DemoDB2/Views/NEWs/Edit.cshtml
@model DemoDB2.Models.NEW

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Sửa tin tức</h6>
            </div>
            <div class="card-body">


                @using (Html.BeginForm("Edit", "NEWs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thông tin tin tức</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.new_id)
                        @Html.HiddenFor(model => model.new_created_by)


                        <div class="form-group">
                            @Html.LabelFor(model => model.tag_id, "tag_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("tag_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.tag_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.new_catalog_id, "new_catalog_id", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("new_catalog_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.new_catalog_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.new_created_by, "new_created_by", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("new_created_by", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.new_created_by, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.tittle, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.tittle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tittle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.new_image, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <img src="@Url.Content(Model.new_image)" width="150" height="150" id="previewImg" />
                                <input type="file" name="UploadImage" onchange="ChangeImage(this, document.getElementById('previewImg'))" />
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<div class="form-group">
                                @Html.LabelFor(model => model.new_created, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.new_created, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.new_created, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Về Danh sách", "Index")
                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                    <!-- Bootstrap core JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery/jquery.min.js"></script>
                    <script src="~/Content/loginassets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                    <!-- Core plugin JavaScript-->
                    <script src="~/Content/loginassets/vendor/jquery-easing/jquery.easing.min.js"></script>

                    <!-- Custom scripts for all pages-->
                    <script src="~/Content/loginassets/js/sb-admin-2.min.js"></script>

                    <!-- Page level plugins -->
                    <script src="~/Content/loginassets/vendor/datatables/jquery.dataTables.min.js"></script>
                    <script src="~/Content/loginassets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

                    <!-- Page level custom scripts -->
                    <script src="~/Content/loginassets/js/demo/datatables-demo.js"></script>
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->